spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=TWOJ_MAIL@gmail.com
spring.mail.password=TWOJE_HASLO_APLIKACJI
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:./data/kirkdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true